# Generated by Django 3.2 on 2021-05-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_duration',
            field=models.TimeField(default=datetime.time(0, 50)),
        ),
    ]
