# Generated by Django 3.2 on 2021-05-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_class_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_duration',
        ),
    ]
