# Generated by Django 3.2.3 on 2021-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classes_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
