# Generated by Django 3.2.3 on 2021-05-28 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210527_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_pub_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
