# Generated by Django 3.2.3 on 2021-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_day_class_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='class_day',
        ),
        migrations.AddField(
            model_name='day',
            name='Friday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Monday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Saturday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Sunday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Thursday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Tuesday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='Wednesday',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
