# Generated by Django 3.2.3 on 2021-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20210530_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Friday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Monday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Saturday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Sunday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Thursday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Tuesday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Wednesday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
