# Generated by Django 3.2.3 on 2021-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_classes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_pub_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
